name: Create Issue Branch
on:
  issues:
    types: [assigned]

jobs:
  create_issue_branch_job:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: create issue branch
        id: create_issue_branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}